# ------------------------------------------------------------------
# CONFIGURACIÓN MÍNIMA Y SEGURA PARA EVITAR ERRORES DE BASE DE DATOS
# ------------------------------------------------------------------

model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: claude-3-5-sonnet-20240620
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY

# Hemos eliminado las secciones 'general_settings' y 'litellm_settings' 
# para usar los valores por defecto de LiteLLM, que no requieren una base de datos.
# Esto es la forma más robusta de solucionar el error "No connected db".

