# litellm-config.yaml (VERSIÓN 100% CORREGIDA)

model_list:
  # El model_name ahora incluye el proveedor para que el backend lo pueda procesar
  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: anthropic/claude-3-5-sonnet-20240620
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY

# Esta sección desactiva la autenticación del proxy.
# Usa espacios normales (dos espacios) para la sangría.
general_settings:
  master_key: "super-secreto-1234"

